CREATE TABLE IF NOT EXISTS `account` (
  `account_id` varchar(40) NOT NULL,
  `account_name` varchar(40) DEFAULT NULL,
  `account_kind` varchar(20) DEFAULT NULL,
  `balance` decimal(18,5) DEFAULT 0,
  `equity` decimal(18,5) DEFAULT 0,
  `gross_pl` decimal(18,5) DEFAULT 0,
  `used_margin` decimal(18,5) DEFAULT 0,
  `usable_margin` decimal(18,5) DEFAULT 0,
  `amount_limit` decimal(18,5) DEFAULT 0,
  `currency` varchar(3) DEFAULT NULL,
  `created` datetime DEFAULT 0,
  `modified` datetime DEFAULT 0,
  PRIMARY KEY (`account_id`)
);

CREATE TABLE IF NOT EXISTS `offer` (
  `offer_id` varchar(40) NOT NULL,
  `symbol` varchar(40) NOT NULL,
  `symbol_type` varchar(20) DEFAULT NULL,
  `bid` decimal(18,6) DEFAULT 0,
  `ask` decimal(18,6) DEFAULT 0,
  `high` decimal(18,6) DEFAULT 0,
  `low` decimal(18,6) DEFAULT 0,
  `volume` int DEFAULT 0,
  `buy_interest` decimal(18,5) DEFAULT 0,
  `sell_interest` decimal(18,5) DEFAULT 0,
  `contract_currency` varchar(3) DEFAULT NULL,
  `digits` int DEFAULT 0,
  `point_size` decimal(10,6) DEFAULT 0,
  `pip_cost` decimal(10,5) DEFAULT 0,
  `contract_multiplier` int DEFAULT 0,
  `time` datetime DEFAULT 0,
  `created` datetime DEFAULT 0,
  `modified` datetime DEFAULT 0,
  PRIMARY KEY (`offer_id`)
);

CREATE TABLE IF NOT EXISTS `order` (
  `order_id` varchar(40) NOT NULL,
  `request_id` varchar(256) DEFAULT NULL,
  `account_id` varchar(40) NOT NULL,
  `offer_id` varchar(40) DEFAULT NULL,
  `trade_id` varchar(40) DEFAULT NULL,
  `side` char(1) DEFAULT NULL,
  `stage` char(1) DEFAULT NULL,
  `type` varchar(10) DEFAULT NULL,
  `order_status` varchar(10) DEFAULT NULL,
  `amount` int DEFAULT 0,
  `rate` decimal(18,6) DEFAULT 0,
  `execution_rate` decimal(18,6) DEFAULT 0,
  `rate_min` decimal(18,6) DEFAULT 0,
  `rate_max` decimal(18,6) DEFAULT 0,
  `stop` decimal(18,6) DEFAULT 0,
  `limit` decimal(18,6) DEFAULT 0,
  `status_time` datetime DEFAULT 0,
  `primary_id` varchar(40) DEFAULT NULL,
  `origin_amount` int DEFAULT 0,
  `filled_amount` int DEFAULT 0,
  `created` datetime DEFAULT 0,
  `modified` datetime DEFAULT 0,
  PRIMARY KEY (`account_id`, `order_id`)
);

CREATE TABLE IF NOT EXISTS `position` (
  `trade_id` varchar(40) NOT NULL,
  `account_id` varchar(40) NOT NULL,
  `offer_id` varchar(40) DEFAULT NULL,
  `amount` int DEFAULT 0,
  `side` char(1) DEFAULT NULL,
  `open_rate` decimal(18,6) DEFAULT 0,
  `open_time` datetime DEFAULT 0,
  `used_margin` decimal(18,5) DEFAULT 0,
  `pl` decimal(18,5) DEFAULT 0,
  `gross_pl` decimal(18,5) DEFAULT 0,
  `close` decimal(18,6) DEFAULT 0,
  `stop` decimal(18,6) DEFAULT 0,
  `limit` decimal(18,6) DEFAULT 0,
  `high` decimal(18,6) DEFAULT 0,
  `low` decimal(18,6) DEFAULT 0,
  `open_quote_id` varchar(256) DEFAULT NULL,
  `open_order_id` varchar(40) DEFAULT NULL,
  `open_order_req_id` varchar(256) DEFAULT NULL,
  `commission` decimal(18,5) DEFAULT 0,
  `rollover_interest` decimal(18,5) DEFAULT 0,
  `trade_id_origin` varchar(40) DEFAULT NULL,
  `created` datetime DEFAULT 0,
  `modified` datetime DEFAULT 0,
  PRIMARY KEY (`account_id`, `trade_id`)
);

CREATE TABLE IF NOT EXISTS `closed_position` (
  `trade_id` varchar(40) NOT NULL,
  `account_id` varchar(40) NOT NULL,
  `offer_id` varchar(40) DEFAULT NULL,
  `amount` int DEFAULT 0,
  `side` char(1) DEFAULT NULL,
  `open_rate` decimal(18,6) DEFAULT 0,
  `open_time` datetime DEFAULT 0,
  `pl` decimal(18,5) DEFAULT 0,
  `net_pl` decimal(18,5) DEFAULT 0,
  `gross_pl` decimal(18,5) DEFAULT 0,
  `open_quote_id` varchar(256) DEFAULT NULL,
  `open_order_id` varchar(40) DEFAULT NULL,
  `open_order_req_id` varchar(256) DEFAULT NULL,
  `close_rate` decimal(18,6) DEFAULT 0,
  `close_time` datetime DEFAULT 0,
  `close_quote_id` varchar(256) DEFAULT NULL,
  `close_order_id` varchar(40) DEFAULT NULL,
  `close_order_req_id` varchar(256) DEFAULT NULL,
  `commission` decimal(18,5) DEFAULT 0,
  `rollover_interest` decimal(18,5) DEFAULT 0,
  `trade_id_origin` varchar(40) DEFAULT NULL,
  `trade_id_remain` varchar(40) DEFAULT NULL,
  `created` datetime DEFAULT 0,
  `modified` datetime DEFAULT 0,
  PRIMARY KEY (`account_id`, `trade_id`)
);
