CREATE TABLE IF NOT EXISTS `account` (
  `account_id` text NOT NULL,
  `account_name` text DEFAULT NULL,
  `account_kind` text DEFAULT NULL,
  `balance` real DEFAULT 0,
  `equity` real DEFAULT 0,
  `gross_pl` real DEFAULT 0,
  `used_margin` real DEFAULT 0,
  `usable_margin` real DEFAULT 0,
  `amount_limit` real DEFAULT 0,
  `currency` text DEFAULT NULL,
  `created` text DEFAULT NULL,
  `modified` text DEFAULT NULL,
  PRIMARY KEY (`account_id`)
);

CREATE TABLE IF NOT EXISTS `offer` (
  `offer_id` text NOT NULL,
  `symbol` text NOT NULL,
  `symbol_type` text DEFAULT NULL,
  `bid` real DEFAULT 0,
  `ask` real DEFAULT 0,
  `high` real DEFAULT 0,
  `low` real DEFAULT 0,
  `volume` integer DEFAULT 0,
  `buy_interest` real DEFAULT 0,
  `sell_interest` real DEFAULT 0,
  `contract_currency` text DEFAULT NULL,
  `digits` integer DEFAULT 0,
  `point_size` real DEFAULT 0,
  `pip_cost` real DEFAULT 0,
  `contract_multiplier` integer DEFAULT 0,
  `time` text DEFAULT NULL,
  `created` text DEFAULT NULL,
  `modified` text DEFAULT NULL,
  PRIMARY KEY (`offer_id`)
);

CREATE TABLE IF NOT EXISTS `order` (
  `order_id` text NOT NULL,
  `request_id` text DEFAULT NULL,
  `account_id` text NOT NULL,
  `offer_id` text DEFAULT NULL,
  `trade_id` text DEFAULT NULL,
  `side` text DEFAULT NULL,
  `stage` text DEFAULT NULL,
  `type` text DEFAULT NULL,
  `order_status` text DEFAULT NULL,
  `amount` integer DEFAULT 0,
  `rate` real DEFAULT 0,
  `execution_rate` real DEFAULT 0,
  `rate_min` real DEFAULT 0,
  `rate_max` real DEFAULT 0,
  `stop` real DEFAULT 0,
  `limit` real DEFAULT 0,
  `status_time` text DEFAULT NULL,
  `primary_id` text DEFAULT NULL,
  `origin_amount` integer DEFAULT 0,
  `filled_amount` integer DEFAULT 0,
  `created` text DEFAULT NULL,
  `modified` text DEFAULT NULL,
  PRIMARY KEY (`account_id`, `order_id`)
);

CREATE TABLE IF NOT EXISTS `position` (
  `trade_id` text NOT NULL,
  `account_id` text NOT NULL,
  `offer_id` text DEFAULT NULL,
  `amount` integer DEFAULT 0,
  `side` text DEFAULT NULL,
  `open_rate` real DEFAULT 0,
  `open_time` text DEFAULT NULL,
  `used_margin` real DEFAULT 0,
  `pl` real DEFAULT 0,
  `gross_pl` real DEFAULT 0,
  `close` real DEFAULT 0,
  `stop` real DEFAULT 0,
  `limit` real DEFAULT 0,
  `high` real DEFAULT 0,
  `low` real DEFAULT 0,
  `open_quote_id` text DEFAULT NULL,
  `open_order_id` text DEFAULT NULL,
  `open_order_req_id` text DEFAULT NULL,
  `commission` real DEFAULT 0,
  `rollover_interest` real DEFAULT 0,
  `trade_id_origin` text DEFAULT NULL,
  `created` text DEFAULT NULL,
  `modified` text DEFAULT NULL,
  PRIMARY KEY (`account_id`, `trade_id`)
);

CREATE TABLE IF NOT EXISTS `closed_position` (
  `trade_id` text NOT NULL,
  `account_id` text NOT NULL,
  `offer_id` text DEFAULT NULL,
  `amount` integer DEFAULT 0,
  `side` text DEFAULT NULL,
  `open_rate` real DEFAULT 0,
  `open_time` text DEFAULT NULL,
  `pl` real DEFAULT 0,
  `net_pl` real DEFAULT 0,
  `gross_pl` real DEFAULT 0,
  `open_quote_id` text DEFAULT NULL,
  `open_order_id` text DEFAULT NULL,
  `open_order_req_id` text DEFAULT NULL,
  `close_rate` real DEFAULT 0,
  `close_time` text DEFAULT NULL,
  `close_quote_id` text DEFAULT NULL,
  `close_order_id` text DEFAULT NULL,
  `close_order_req_id` text DEFAULT NULL,
  `commission` real DEFAULT 0,
  `rollover_interest` real DEFAULT 0,
  `trade_id_origin` text DEFAULT NULL,
  `trade_id_remain` text DEFAULT NULL,
  `created` text DEFAULT NULL,
  `modified` text DEFAULT NULL,
  PRIMARY KEY (`account_id`, `trade_id`)
);
